version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: knapp_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - knapp-mysql-data:/var/lib/mysql
    networks:
      - knapp-network

volumes:
  knapp-mysql-data:

networks:
  knapp-network:
    driver: bridge
