<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up()
    {
        DB::statement("
            CREATE TABLE companies (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(255),
                cnpj VARCHAR2(16) UNIQUE,
                phone_number VARCHAR2(15),
                email VARCHAR2(255) UNIQUE,
                uf VARCHAR2(2),
                endereco_detail VARCHAR2(255),
                status NUMBER(1) DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP,
                deleted_at TIMESTAMP
            )
        ");
    }

    public function down()
    {
        DB::statement("DROP TABLE companies CASCADE CONSTRAINTS");
    }
};
