<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up()
    {
        DB::statement("
            CREATE TABLE branches (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                company_id NUMBER NOT NULL,
                name VARCHAR2(255),
                cnpj VARCHAR2(14) UNIQUE,
                phone_number VARCHAR2(15),
                email VARCHAR2(255) UNIQUE,
                uf VARCHAR2(2),
                endereco_detail VARCHAR2(255),
                status NUMBER(1) DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP,
                deleted_at TIMESTAMP,
                CONSTRAINT fk_branch_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
            )
        ");
    }

    public function down()
    {
        DB::statement("DROP TABLE branches CASCADE CONSTRAINTS");
    }
};
