<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up()
    {
        DB::statement("
            CREATE TABLE users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(255),
                cpf VARCHAR2(12) UNIQUE,
                phone_number VARCHAR2(15),
                is_admin NUMBER(1) DEFAULT 0,
                company_id NUMBER,
                branch_id NUMBER,
                uf VARCHAR2(2),
                endereco_detail VARCHAR2(255),
                email VARCHAR2(255) UNIQUE,
                status NUMBER(1) DEFAULT 0,
                email_verified_at TIMESTAMP NULL,
                password VARCHAR2(255),
                remember_token VARCHAR2(100),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP,
                deleted_at TIMESTAMP,
                CONSTRAINT fk_user_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
                CONSTRAINT fk_user_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
            )
        ");
    }

    public function down()
    {
        DB::statement("DROP TABLE users CASCADE CONSTRAINTS");
    }
};
