<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up()
    {
        DB::statement("
            CREATE TABLE personal_access_tokens (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tokenable_id NUMBER NOT NULL,
                tokenable_type VARCHAR2(255) NOT NULL,
                name VARCHAR2(255),
                token VARCHAR2(64) UNIQUE,
                abilities CLOB NULL,
                last_used_at TIMESTAMP NULL,
                expires_at TIMESTAMP NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP
            )
        ");

        DB::statement("
            CREATE INDEX idx_tokenable_type_id ON personal_access_tokens (tokenable_type, tokenable_id)
        ");
    }

    public function down()
    {
        DB::statement("DROP TABLE personal_access_tokens CASCADE CONSTRAINTS");
    }
};
